/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pss.imagem.processamento.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Thiago
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        this.setLocationRelativeTo(this.getParent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        painelLateral = new javax.swing.JPanel();
        imagemAzul = new javax.swing.JCheckBox();
        imagemVerde = new javax.swing.JCheckBox();
        imagemVermelha = new javax.swing.JCheckBox();
        imagemEspelhada = new javax.swing.JCheckBox();
        rotacaoEmGraus = new javax.swing.JCheckBox();
        NegativoImagem = new javax.swing.JCheckBox();
        sepia = new javax.swing.JCheckBox();
        pixelar = new javax.swing.JCheckBox();
        tonsDeCinza = new javax.swing.JCheckBox();
        brilho = new javax.swing.JCheckBox();
        blur = new javax.swing.JCheckBox();
        glowingBlur = new javax.swing.JCheckBox();
        binarizar = new javax.swing.JCheckBox();
        painelBotoes = new javax.swing.JPanel();
        btnAbrir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnDesfazer = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        painelFoto = new javax.swing.JPanel();
        filtrosLabel = new javax.swing.JLabel();
        builderComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelLateral.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        imagemAzul.setForeground(new java.awt.Color(255, 0, 0));
        imagemAzul.setText("Imagem Azul");

        imagemVerde.setForeground(new java.awt.Color(255, 0, 0));
        imagemVerde.setText("Imagem Verde");

        imagemVermelha.setForeground(new java.awt.Color(255, 0, 0));
        imagemVermelha.setText("Imagem Vermelha");

        imagemEspelhada.setText("Imagem Espelhada");

        rotacaoEmGraus.setForeground(new java.awt.Color(255, 0, 0));
        rotacaoEmGraus.setText("Rotacao da Imagem em graus °");

        NegativoImagem.setText("Negativo da Imagem");

        sepia.setForeground(new java.awt.Color(255, 0, 0));
        sepia.setText("Aplicar a cor Sepia");

        pixelar.setForeground(new java.awt.Color(255, 0, 0));
        pixelar.setText("Pixelar Imagem");

        tonsDeCinza.setForeground(new java.awt.Color(255, 0, 0));
        tonsDeCinza.setText("Tons de Cinza");

        brilho.setForeground(new java.awt.Color(255, 0, 0));
        brilho.setText("Aplicar Brilho");

        blur.setForeground(new java.awt.Color(255, 0, 0));
        blur.setText("Aplicar Blur");

        glowingBlur.setForeground(new java.awt.Color(255, 0, 0));
        glowingBlur.setText("Aplicar Glowing Blur");

        binarizar.setForeground(new java.awt.Color(255, 0, 0));
        binarizar.setText("Binarizar Imagem");

        javax.swing.GroupLayout painelLateralLayout = new javax.swing.GroupLayout(painelLateral);
        painelLateral.setLayout(painelLateralLayout);
        painelLateralLayout.setHorizontalGroup(
            painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagemAzul)
                    .addComponent(imagemVerde)
                    .addComponent(imagemVermelha)
                    .addComponent(imagemEspelhada)
                    .addComponent(rotacaoEmGraus)
                    .addComponent(NegativoImagem)
                    .addComponent(sepia)
                    .addComponent(pixelar)
                    .addComponent(tonsDeCinza)
                    .addComponent(brilho)
                    .addComponent(blur)
                    .addComponent(glowingBlur)
                    .addComponent(binarizar))
                .addContainerGap())
        );
        painelLateralLayout.setVerticalGroup(
            painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagemAzul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagemVerde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imagemVermelha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imagemEspelhada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rotacaoEmGraus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NegativoImagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pixelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tonsDeCinza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(brilho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(glowingBlur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(binarizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAbrir.setText("Abrir Imagem");

        btnSalvar.setText("Salvar como");

        btnDesfazer.setText("Desfazer");

        btnRestaurar.setText("Restaurar Padrão");

        btnFechar.setText("Fechar");

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(btnAbrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDesfazer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRestaurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrir)
                    .addComponent(btnSalvar)
                    .addComponent(btnDesfazer)
                    .addComponent(btnRestaurar)
                    .addComponent(btnFechar))
                .addContainerGap())
        );

        painelFoto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imagem", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        filtrosLabel.setText("Conjunto de Filtros pré-definidos:");

        jScrollPane1.setViewportView(labelImagem);

        javax.swing.GroupLayout painelFotoLayout = new javax.swing.GroupLayout(painelFoto);
        painelFoto.setLayout(painelFotoLayout);
        painelFotoLayout.setHorizontalGroup(
            painelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filtrosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(builderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        painelFotoLayout.setVerticalGroup(
            painelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtrosLabel)
                    .addComponent(builderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox NegativoImagem;
    private javax.swing.JCheckBox binarizar;
    private javax.swing.JCheckBox blur;
    private javax.swing.JCheckBox brilho;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnDesfazer;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> builderComboBox;
    private javax.swing.JLabel filtrosLabel;
    private javax.swing.JCheckBox glowingBlur;
    private javax.swing.JCheckBox imagemAzul;
    private javax.swing.JCheckBox imagemEspelhada;
    private javax.swing.JCheckBox imagemVerde;
    private javax.swing.JCheckBox imagemVermelha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelFoto;
    private javax.swing.JPanel painelLateral;
    private javax.swing.JCheckBox pixelar;
    private javax.swing.JCheckBox rotacaoEmGraus;
    private javax.swing.JCheckBox sepia;
    private javax.swing.JCheckBox tonsDeCinza;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getNegativoImagem() {
        return NegativoImagem;
    }

    public JCheckBox getBinarizar() {
        return binarizar;
    }

    public JCheckBox getBlur() {
        return blur;
    }

    public JCheckBox getBrilho() {
        return brilho;
    }

    public JButton getBtnAbrir() {
        return btnAbrir;
    }

    public JButton getBtnDesfazer() {
        return btnDesfazer;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public JButton getBtnRestaurar() {
        return btnRestaurar;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public JComboBox<String> getBuilderComboBox() {
        return builderComboBox;
    }

    public JLabel getFiltrosLabel() {
        return filtrosLabel;
    }

    public JCheckBox getGlowingBlur() {
        return glowingBlur;
    }

    public JCheckBox getImagemAzul() {
        return imagemAzul;
    }

    public JCheckBox getImagemEspelhada() {
        return imagemEspelhada;
    }

    public JCheckBox getImagemVerde() {
        return imagemVerde;
    }

    public JCheckBox getImagemVermelha() {
        return imagemVermelha;
    }

    public JLabel getLabelImagem() {
        return labelImagem;
    }

    public JPanel getPainelBotoes() {
        return painelBotoes;
    }

    public JPanel getPainelFoto() {
        return painelFoto;
    }

    public JPanel getPainelLateral() {
        return painelLateral;
    }

    public JCheckBox getPixelar() {
        return pixelar;
    }

    public JCheckBox getRotacaoEmGraus() {
        return rotacaoEmGraus;
    }

    public JCheckBox getSepia() {
        return sepia;
    }

    public JCheckBox getTonsDeCinza() {
        return tonsDeCinza;
    }
}
